#
# @author Daniel Marcenco (danielm@saltedge.com)
# Copyright (c) 2022 Salt Edge.
#

development: &common_settings
  push_service_url:
  push_service_app_id:
  push_service_app_secret:
  service_url: "service_url"
  sca_service_url: "sca_service_url"
  sca_public_key: "sca_public_rsa_development.pem"
  app_private_key: "app_private_rsa_development.pem"
  provider_id: "provider_id"
  sidekiq:
    port: 6379
    host: "redis"
    database: 0
    namespace: "demo_sca_provider"
    password: ""
  redis:
    port: 6379
    host: "redis"
    database: 0
    password: ""
test:
  <<: *common_settings
production:
  <<: *common_settings
